jobs:

######################### NATIVE WAR CI/CD JOBS #########################

# runCI job that builds and pushes artifact to S3
  - name: java-ecr-runcli-elasticbeanstalk_runCI
    type: runCI
    steps:
      - OUT: demo_java_ecr_img 

# runCLI job that deploys image in ECR to Elastic Beanstalk - TEST
  - name: demo_java_ecr_test_deploy
    type: runCLI
    steps:
      - IN: demo_java_ecr_awscli
      - IN: demo_java_ecr_gitrepo
      - IN: demo_java_ecr_img
      - IN: demo_java_ecr_params
      - IN: demo_java_ecr_params_test
      - TASK:
        # update Dockerrun.aws.json file with values 
        - script: export ENVIRONMENT=$DEMO_JAVA_ECR_PARAMS_TEST_ENVIRONMENT PORT=$DEMO_JAVA_ECR_PARAMS_TEST_PORT
        - script: ls -l $DEMO_JAVA_ECR_GITREPO_PATH
        - script: shippable_replace $DEMO_JAVA_ECR_GITREPO_PATH/Dockerrun.aws.json 
        - script: cat $DEMO_JAVA_ECR_GITREPO_PATH/Dockerrun.aws.json
        - script: eb deploy
        # # save latest deployment to state
        # - script: echo -e "LATEST_TEST_DEPLOY=$DEMO_JAVA_ECR_IMG_VERSIONNAME" >> $DEMO_JAVA_ECR_TEST_DEPLOY_STATE/latest_test_deploy.env

# # runCLI job that deploys image in ECR to Elastic Beanstalk
# # based on previous deployment to TEST environment
#   - name: demo_java_ecr_prod_deploy
#     type: runCLI
#     steps:
#       - IN: demo_java_ecr_test_deploy
#         switch: off
#       - IN: demo_java_ecr_img
#         switch: off
#       - IN: demo_java_ecr_awscli
#       - TASK:
#         # load last build version deployed to test from incoming state file
#         - script:
#         # display location of latest build in S3
#         - script:
#         # download latest build file to job
#         - script:
#         # create identity file from credentials injected for VM cluster
#         - script:
#         # for each node in the Node Cluster, deploy the latest build file
#         - script:
#
